### ISSUE TITLE
Predict_output.csv problem

### ISSUE THREAD

**Issue by caiquanyou** [Su-informatics-lab/DSTG#1]
Hi:
I run the demo, and get the preddict_output result all Nan.
How to fix it ?

**Comment by jing-su** [comment]
Hi, 

Thanks for your interest in our tool. I am copying you email with Dr Song. 

Thanks! 

Jing

**Comment by QSong-github** [comment]
Any error have you got? Have you run the "Rscript convert_data.R" to load data first?

**Comment by caiquanyou** [comment]
Hi ,Dr song
I run the demo, and&nbsp;&nbsp;run the "Rscript convert_data.R" to load data first and get the infor_data ;
and then run python train.py
and get the preddict_output.csv result all Nan since the&nbsp; true_output.csv have values
and I&nbsp; could not figurre out what is going wrong and How to fix it ?
THanks!






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Su-informatics-lab/DSTG"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月30日(星期五) 晚上9:23
收件人:&nbsp;"Su-informatics-lab/DSTG"<DSTG@noreply.github.com&gt;;
抄送:&nbsp;"xianmao"<951463554@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Su-informatics-lab/DSTG] Predict_output.csv problem (#1)





 
Any error have you got? Have you run the "Rscript convert_data.R" to load data first?

**Comment by QSong-github** [comment]
What about giving me your email then we can discuss and look into the result?

**Comment by caiquanyou** [comment]
Thanks, my email is 13172055914@126.com


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Su-informatics-lab/DSTG"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月2日(星期一) 上午10:21
收件人:&nbsp;"Su-informatics-lab/DSTG"<DSTG@noreply.github.com&gt;;
抄送:&nbsp;"xianmao"<951463554@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Su-informatics-lab/DSTG] Predict_output.csv problem (#1)





 
What about giving me your email then we can discuss and look into the result?
