### ISSUE TITLE
what filterEdge filters?

### ISSUE THREAD

**Issue by Boxedpig** [Su-informatics-lab/DSTG#10]
Hi Su,

Thanks for you and your team for developing this powerful tool. But I have a question about "filterEdge" function:

`  def filterEdge(edges, neighbors, mats, features, k_filter):
    
    nn_spots1 = neighbors[4]
    nn_spots2 = neighbors[5]
    mat1 = mats.loc[features, nn_spots1].transpose()
    mat2 = mats.loc[features, nn_spots2].transpose()
    cn_data1 = l2norm(mat1)
    cn_data2 = l2norm(mat2)
    nn = kNN(data=cn_data2.loc[nn_spots2, ],
             query=cn_data1.loc[nn_spots1, ],
             k=k_filter)
    position = [
        np.where(
            edges.loc[:, "spot2"][x] == nn[1][edges.loc[:, 'spot1'][x], ])[0]
        for x in range(edges.shape[0])
    ]
    nps = np.concatenate(position, axis=0)
    fedge = edges.iloc[nps, ]
    return (fedge)`

As I understand it, this function aims to ensure the relationships between spots are also kept when genes are restircted to top variable genes. However, I think _np.where_ in line 12 returns the postion of _nn[1]_ matrix if spot1 exists and this position itself dosen't match the position of edges, which makes this filter seem meaningless. Maybe what you want to return is the position of  vector in _edges_ if two spots are also adjacent in _nn_.
I am not sure I got that right. So, looking forward to your reply.

Bests,
Chang

**Comment by QSong-github** [comment]
> Hi Su,
> 
> Thanks for you and your team for developing this powerful tool. But I have a question about "filterEdge" function:
> 
> ` def filterEdge(edges, neighbors, mats, features, k_filter):
> 
> ```
> nn_spots1 = neighbors[4]
> nn_spots2 = neighbors[5]
> mat1 = mats.loc[features, nn_spots1].transpose()
> mat2 = mats.loc[features, nn_spots2].transpose()
> cn_data1 = l2norm(mat1)
> cn_data2 = l2norm(mat2)
> nn = kNN(data=cn_data2.loc[nn_spots2, ],
>          query=cn_data1.loc[nn_spots1, ],
>          k=k_filter)
> position = [
>     np.where(
>         edges.loc[:, "spot2"][x] == nn[1][edges.loc[:, 'spot1'][x], ])[0]
>     for x in range(edges.shape[0])
> ]
> nps = np.concatenate(position, axis=0)
> fedge = edges.iloc[nps, ]
> return (fedge)`
> ```
> 
> As I understand it, this function aims to ensure the relationships between spots are also kept when genes are restircted to top variable genes. However, I think _np.where_ in line 12 returns the postion of _nn[1]_ matrix if spot1 exists and this position itself dosen't match the position of edges, which makes this filter seem meaningless. Maybe what you want to return is the position of vector in _edges_ if two spots are also adjacent in _nn_. I am not sure I got that right. So, looking forward to your reply.
> 
> Bests, Chang

Thanks for the interest. This function returns the edges that are adjacent as nearest neighbors.

**Comment by RemyLau** [comment]
> However, I think np.where in line 12 returns the postion of nn[1] matrix if spot1 exists and this position itself dosen't match the position of edges, which makes this filter seem meaningless.

I have the exact same concern with @Boxedpig. This position list `position` is supposed to be used for subsampling the full edge lists `edges`. However, the current implementation is incorrect and will result in redundant edges after the indexing `edges.iloc[nps]` because `nps` do not contain indexes to the filtered edges, but rather, neighbor index of the queried spot `spot1`.

**Comment by QSong-github** [comment]
> > However, I think np.where in line 12 returns the postion of nn[1] matrix if spot1 exists and this position itself dosen't match the position of edges, which makes this filter seem meaningless.
> 
> I have the exact same concern with @Boxedpig. This position list `position` is supposed to be used for subsampling the full edge lists `edges`. However, the current implementation is incorrect and will result in redundant edges after the indexing `edges.iloc[nps]` because `nps` do not contain indexes to the filtered edges, but rather, neighbor index of the queried spot `spot1`.

Thanks for the comment. I will look into the filter function about the index matching. Basically, the filter is to return is the position of vector in edges if two spots are also adjacent in nn.
