### ISSUE TITLE
Number of genes in the ST dataset

### ISSUE THREAD

**Issue by weifangliu** [Su-informatics-lab/DSTG#12]
Hi, can I run DSTG with only a few dozen genes in my ST dataset? I tried to modify the default number of features in R_utils.R and I could ran `convert_data.R`, but runnning `train.py` gave me NA results.

**Comment by QSong-github** [comment]
Please first run the demo data. If it works for you, there should be no issues. Also, you can use the output data of demo example to evaluate/compare the output of your own data, maybe some formatting issues.

**Comment by weifangliu** [comment]
Thanks for your reply. I have run the demo data and it worked with no issues. I think the problem is that the program uses 2,000 HVGs by default, so there will be some problems when we input fewer than 2,000 genes. I found that in convert_data.R line 17 `Convert_Data(synthetic.count,synthetic.label,anova=FALSE)` specifies anova=FALSE with the demo data and line 27 `Convert_Data(count.list,label.list,anova=TRUE)` specifies anova=TRUE for user input data, therefore if we input our own data, it will always run `sel.features <- select_feature(st_count[[1]],st_label[[1]])` in line 93 of R_utils.R where the `select_feature` function has a default number of features as 2,000. Am I making sense? Can we have user input data with <2,000 genes?

**Comment by QSong-github** [comment]
> default

Yes definitely. You can change the number of selected features by adding argument (nf =2000 or 1000) in line 93.
