### ISSUE TITLE
Problem with Matrix Subsetting in convert_data.R

### ISSUE THREAD

**Issue by manandraj20** [Su-informatics-lab/DSTG#13]
I am trying to run DSTG on my private transcriptomic dataset but the attempt is throwing an error.
```
Rscript convert_data.R "C:\Users\Milan Anand Raj\Desktop\sc_count.RDS" "C:\Users\Milan Anand Raj\Desktop\st_count.RDS" "C:\Users\Milan Anand Raj\Desktop\sc_label.RDS
```
The command line code.

```
Error in sc.count[intersect.genes, ] :
  invalid or not-yet-implemented 'Matrix' subsetting
Calls: [ -> [
Execution halted
```
The Error.

Any help is appreciated.
Thank You.

**Comment by QSong-github** [comment]
Did you try running the codes with the example data? It might be the data formatting issue.
