### ISSUE TITLE
'test_spot_fun' is no longer supported

### ISSUE THREAD

**Issue by yl883** [Su-informatics-lab/DSTG#14]
Hi, 

I was trying to run the convert_data.R step by step and I encounter the error:
Error: 'test_spot_fun' is not an exported object from 'namespace:SPOTlight'
I checked the SPOTlight and it seems that this function no longer exists in their latest package now. Can you help with that?

Edit: I found this archived function from their github, but I am not sure it is the correct version of this function.

Thank you

**Comment by QSong-github** [comment]
> Hi,
> 
> I was trying to run the convert_data.R step by step and I encounter the error: Error: 'test_spot_fun' is not an exported object from 'namespace:SPOTlight' I checked the SPOTlight and it seems that this function no longer exists in their latest package now. Can you help with that?
> 
> Edit: I found this archived function from their github, but I am not sure it is the correct version of this function.
> 
> Thank you

Hi there, I updated the "R_utils.R" script with the "test_spot_fun" function included.
