### ISSUE TITLE
The demo fails to run

### ISSUE THREAD

**Issue by ZDDWLIG** [Su-informatics-lab/DSTG#15]
Thanks for the great job.I had some problems in running the demo.With all packages in requirments.txt installed,the convert_data.R still can't generate data.The error are as follow:

<img width="738" alt="1ef9906867ab992e3a9719bb72e22fd" src="https://user-images.githubusercontent.com/88024901/209279249-bc518abf-2223-41f1-8735-007cd2bad64f.png">

**Comment by jing-su** [comment]
It looks that the file “Variable_features.csv” was not generated. Just wonder whether your have run the step: cd DSTG
Rscript convert_data.R # load example data 
You should find generated data files under DSTG/Info_data if this step is successful. Thanks! Jing Sent from my iPhoneOn Dec 23, 2022, at 12:50 AM, ZDDWLIG ***@***.***> wrote:﻿
Thanks for the great job.I had some problems in running the demo.With all packages in requirments.txt installed,the convert_data.R still can't generate data.The error are as follow:
