### ISSUE TITLE
Question regarding the link-graph usage in the main training script

### ISSUE THREAD

**Issue by RemyLau** [Su-informatics-lab/DSTG#16]
According to the link-graph construction description on the paper, it contains interaction (1) between pseudo-spots and real-spots, and (2) between real-spots. 

<img width="639" alt="image" src="https://user-images.githubusercontent.com/36778645/210149976-c16cfab0-a592-441b-9c93-62617c83aa83.png">

If I understood correctly, `graph1` corresponds to (1) and `graph2` corresponds to (2).

https://github.com/Su-informatics-lab/DSTG/blob/4a2f958a87ba3137c3ffa75188563af3e0245a5a/DSTG/graph.py#L89-L95

However, in the main training script, _**only `graph1` is used**_.

https://github.com/Su-informatics-lab/DSTG/blob/4a2f958a87ba3137c3ffa75188563af3e0245a5a/DSTG/train.py#L34-L37

Because `load_data` only loads `graph1`

https://github.com/Su-informatics-lab/DSTG/blob/4a2f958a87ba3137c3ffa75188563af3e0245a5a/DSTG/utils.py#L73-L99

I'm wondering if this is done intentionally or accidentally. I appreciate if you could clarify this confusion due to the inconsistency between the code and the manuscript. Thank you for any help in advance!

**Comment by QSong-github** [comment]
> According to the link-graph construction description on the paper, it contains interaction (1) between pseudo-spots and real-spots, and (2) between real-spots.
> 
> <img alt="image" width="639" src="https://user-images.githubusercontent.com/36778645/210149976-c16cfab0-a592-441b-9c93-62617c83aa83.png">
> 
> If I understood correctly, `graph1` corresponds to (1) and `graph2` corresponds to (2).
> 
> https://github.com/Su-informatics-lab/DSTG/blob/4a2f958a87ba3137c3ffa75188563af3e0245a5a/DSTG/graph.py#L89-L95
> 
> However, in the main training script, _**only `graph1` is used**_.
> 
> https://github.com/Su-informatics-lab/DSTG/blob/4a2f958a87ba3137c3ffa75188563af3e0245a5a/DSTG/train.py#L34-L37
> 
> Because `load_data` only loads `graph1`
> 
> https://github.com/Su-informatics-lab/DSTG/blob/4a2f958a87ba3137c3ffa75188563af3e0245a5a/DSTG/utils.py#L73-L99
> 
> I'm wondering if this is done intentionally or accidentally. I appreciate if you could clarify this confusion due to the inconsistency between the code and the manuscript. Thank you for any help in advance!

Hi there, yes two graphs are used in our method. You may need merge graph1 & 2 as graphs (previous graph1) in the load_data function? It should be a typo and I will correct.

**Comment by RemyLau** [comment]
Thanks for the clarification!
