### ISSUE TITLE
Error on synthetic dataset

### ISSUE THREAD

**Issue by echang992000** [Su-informatics-lab/DSTG#2]
I am receiving the following error when I run the synthetic dataset:

```
C:\Users\echan\Desktop\spatiogenomics\DSTG\DSTG\Infor_Data/ST_count\ST_count_1.csv
C:\Users\echan\Desktop\spatiogenomics\DSTG\DSTG\Infor_Data/ST_count\ST_count_2.csv
C:\Users\echan\Desktop\spatiogenomics\DSTG\DSTG\Infor_Data/ST_norm\ST_norm_1.csv
C:\Users\echan\Desktop\spatiogenomics\DSTG\DSTG\Infor_Data/ST_norm\ST_norm_2.csv
C:\Users\echan\Desktop\spatiogenomics\DSTG\DSTG\Infor_Data/ST_scale\ST_scale_1.csv
C:\Users\echan\Desktop\spatiogenomics\DSTG\DSTG\Infor_Data/ST_scale\ST_scale_2.csv
C:\Users\echan\Desktop\spatiogenomics\DSTG\DSTG\Infor_Data/ST_label\ST_label_1.csv
C:\Users\echan\Desktop\spatiogenomics\DSTG\DSTG\Infor_Data/ST_label\ST_label_2.csv
Traceback (most recent call last):
  File "train.py", line 35, in <module>
    FLAGS.dataset)
  File "C:\Users\echan\Desktop\spatiogenomics\DSTG\DSTG\utils.py", line 13, in load_data
    input_data(datadir)
  File "C:\Users\echan\Desktop\spatiogenomics\DSTG\DSTG\data.py", line 17, in input_data
    Link_Graph(outputdir='Infor_Data')
  File "C:\Users\echan\Desktop\spatiogenomics\DSTG\DSTG\graph.py", line 55, in Link_Graph
    combine=combine)
  File "C:\Users\echan\Desktop\spatiogenomics\DSTG\DSTG\gutils.py", line 161, in Link_graph
    k=30)
  File "C:\Users\echan\Desktop\spatiogenomics\DSTG\DSTG\gutils.py", line 66, in KNN
    embedding_cells1 = cell_embedding.loc[cells1, ]
  File "C:\ProgramData\Anaconda3\envs\tf4\lib\site-packages\pandas\core\indexing.py", line 1472, in __getitem__
    return self._getitem_tuple(key)
  File "C:\ProgramData\Anaconda3\envs\tf4\lib\site-packages\pandas\core\indexing.py", line 879, in _getitem_tuple
    return self._multi_take(tup)
  File "C:\ProgramData\Anaconda3\envs\tf4\lib\site-packages\pandas\core\indexing.py", line 943, in _multi_take
    return o._reindex_with_indexers(d, copy=True, allow_dups=True)
  File "C:\ProgramData\Anaconda3\envs\tf4\lib\site-packages\pandas\core\generic.py", line 3810, in _reindex_with_indexers
    copy=copy)
  File "C:\ProgramData\Anaconda3\envs\tf4\lib\site-packages\pandas\core\internals.py", line 4429, in reindex_indexer
    return self.__class__(new_blocks, new_axes)
  File "C:\ProgramData\Anaconda3\envs\tf4\lib\site-packages\pandas\core\internals.py", line 3282, in __init__
    self._verify_integrity()
  File "C:\ProgramData\Anaconda3\envs\tf4\lib\site-packages\pandas\core\internals.py", line 3493, in _verify_integrity
    construction_error(tot_items, block.shape[1:], self.axes)
  File "C:\ProgramData\Anaconda3\envs\tf4\lib\site-packages\pandas\core\internals.py", line 4843, in construction_error
    passed, implied))
ValueError: Shape of passed values is (30, 2000), indices imply (30, 1000)
```

**Comment by QSong-github** [comment]
What about giving me your email then we can discuss and look into the result?

**Comment by QSong-github** [comment]
> I am receiving the following error when I run the synthetic dataset:
> 
> ```
> C:\Users\echan\Desktop\spatiogenomics\DSTG\DSTG\Infor_Data/ST_count\ST_count_1.csv
> C:\Users\echan\Desktop\spatiogenomics\DSTG\DSTG\Infor_Data/ST_count\ST_count_2.csv
> C:\Users\echan\Desktop\spatiogenomics\DSTG\DSTG\Infor_Data/ST_norm\ST_norm_1.csv
> C:\Users\echan\Desktop\spatiogenomics\DSTG\DSTG\Infor_Data/ST_norm\ST_norm_2.csv
> C:\Users\echan\Desktop\spatiogenomics\DSTG\DSTG\Infor_Data/ST_scale\ST_scale_1.csv
> C:\Users\echan\Desktop\spatiogenomics\DSTG\DSTG\Infor_Data/ST_scale\ST_scale_2.csv
> C:\Users\echan\Desktop\spatiogenomics\DSTG\DSTG\Infor_Data/ST_label\ST_label_1.csv
> C:\Users\echan\Desktop\spatiogenomics\DSTG\DSTG\Infor_Data/ST_label\ST_label_2.csv
> Traceback (most recent call last):
>   File "train.py", line 35, in <module>
>     FLAGS.dataset)
>   File "C:\Users\echan\Desktop\spatiogenomics\DSTG\DSTG\utils.py", line 13, in load_data
>     input_data(datadir)
>   File "C:\Users\echan\Desktop\spatiogenomics\DSTG\DSTG\data.py", line 17, in input_data
>     Link_Graph(outputdir='Infor_Data')
>   File "C:\Users\echan\Desktop\spatiogenomics\DSTG\DSTG\graph.py", line 55, in Link_Graph
>     combine=combine)
>   File "C:\Users\echan\Desktop\spatiogenomics\DSTG\DSTG\gutils.py", line 161, in Link_graph
>     k=30)
>   File "C:\Users\echan\Desktop\spatiogenomics\DSTG\DSTG\gutils.py", line 66, in KNN
>     embedding_cells1 = cell_embedding.loc[cells1, ]
>   File "C:\ProgramData\Anaconda3\envs\tf4\lib\site-packages\pandas\core\indexing.py", line 1472, in __getitem__
>     return self._getitem_tuple(key)
>   File "C:\ProgramData\Anaconda3\envs\tf4\lib\site-packages\pandas\core\indexing.py", line 879, in _getitem_tuple
>     return self._multi_take(tup)
>   File "C:\ProgramData\Anaconda3\envs\tf4\lib\site-packages\pandas\core\indexing.py", line 943, in _multi_take
>     return o._reindex_with_indexers(d, copy=True, allow_dups=True)
>   File "C:\ProgramData\Anaconda3\envs\tf4\lib\site-packages\pandas\core\generic.py", line 3810, in _reindex_with_indexers
>     copy=copy)
>   File "C:\ProgramData\Anaconda3\envs\tf4\lib\site-packages\pandas\core\internals.py", line 4429, in reindex_indexer
>     return self.__class__(new_blocks, new_axes)
>   File "C:\ProgramData\Anaconda3\envs\tf4\lib\site-packages\pandas\core\internals.py", line 3282, in __init__
>     self._verify_integrity()
>   File "C:\ProgramData\Anaconda3\envs\tf4\lib\site-packages\pandas\core\internals.py", line 3493, in _verify_integrity
>     construction_error(tot_items, block.shape[1:], self.axes)
>   File "C:\ProgramData\Anaconda3\envs\tf4\lib\site-packages\pandas\core\internals.py", line 4843, in construction_error
>     passed, implied))
> ValueError: Shape of passed values is (30, 2000), indices imply (30, 1000)
> ```

What about giving me your email then we can discuss and look into the result?

**Comment by QSong-github** [comment]
As following up, I would recommend running DSTG on mac ox or linux system.
