### ISSUE TITLE
Is there an implementation of pytorch version?

### ISSUE THREAD

**Issue by hackerchenzhuo** [Su-informatics-lab/DSTG#4]

**Comment by QSong-github** [comment]
Not yet. We may consider to work on a pytorch version. Thanks for asking.

**Comment by RemyLau** [comment]
Hi @hackerchenzhuo , if you are still interested, we have reimplemented a PyTorch version of DSTG in our DANCE package. You can check out this example run script using DSTG: https://github.com/OmicsML/dance/blob/main/examples/spatial/cell_type_deconvo/dstg.py
