### ISSUE TITLE
PDAC data

### ISSUE THREAD

**Issue by leihouyeung** [Su-informatics-lab/DSTG#5]
Hi @QSong-github ,
Could you please share the data of all spots' coordinates for the tissue images in the PDAC-A and B? I would like to map the spots into images. Thanks a lot!

**Comment by QSong-github** [comment]
You can download the data from this paper, it is open to public. 

_Moncada, Reuben, et al. "Integrating microarray-based spatial transcriptomics and single-cell RNA-seq reveals tissue architecture in pancreatic ductal adenocarcinomas." Nature biotechnology 38.3 (2020): 333-342._

**Comment by leihouyeung** [comment]
> You can download the data from this paper, it is open to public.
> 
> _Moncada, Reuben, et al. "Integrating microarray-based spatial transcriptomics and single-cell RNA-seq reveals tissue architecture in pancreatic ductal adenocarcinomas." Nature biotechnology 38.3 (2020): 333-342._

Thanks for your reply, but I think that is not what I am asking about. I have downloaded all of the data from the paper you sent to me. But I didn't find the coordinates of each spot in the tissue image. I found the relative coordinates of spots, but this could be used to map spots in the tissue image. Thus, I would like to ask that how did you map the spots to tissue images? Thanks!

**Comment by QSong-github** [comment]
> > You can download the data from this paper, it is open to public.
> > _Moncada, Reuben, et al. "Integrating microarray-based spatial transcriptomics and single-cell RNA-seq reveals tissue architecture in pancreatic ductal adenocarcinomas." Nature biotechnology 38.3 (2020): 333-342._
> 
> Thanks for your reply, but I think that is not what I am asking about. I have downloaded all of the data from the paper you sent to me. But I didn't find the coordinates of each spot in the tissue image. I found the relative coordinates of spots, but this could be used to map spots in the tissue image. Thus, I would like to ask that how did you map the spots to tissue images? Thanks!

We empirically aligned the images and spots for visualization. You may reach out to the author for related files if you want  exact match.

**Comment by leihouyeung** [comment]
> > > You can download the data from this paper, it is open to public.
> > > _Moncada, Reuben, et al. "Integrating microarray-based spatial transcriptomics and single-cell RNA-seq reveals tissue architecture in pancreatic ductal adenocarcinomas." Nature biotechnology 38.3 (2020): 333-342._
> > 
> > 
> > Thanks for your reply, but I think that is not what I am asking about. I have downloaded all of the data from the paper you sent to me. But I didn't find the coordinates of each spot in the tissue image. I found the relative coordinates of spots, but this could be used to map spots in the tissue image. Thus, I would like to ask that how did you map the spots to tissue images? Thanks!
> 
> We empirically aligned the images and spots for visualization. You may reach out to the author for related files if you want exact match.

I see. Thanks so much for your response!
