### ISSUE TITLE
PBMC data

### ISSUE THREAD

**Issue by fanyue322** [Su-informatics-lab/DSTG#7]
Hi,

I see that you have provided the simulation details about 13 PBMC scRNAseq data which is super helpful. Could you please share the annotations(cell types) of those scRNAseq data? 

Many Thanks!

**Comment by QSong-github** [comment]
Hello, please refer to the paper: "Benchmarking single-cell RNA-sequencing protocols for cell atlas projects. Nat Biotechnol  2020;38(6):747–55". This paper's authors are responsible for sharing the data.
